spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 995760024175-tl4qnsoi4ecechr40hkeql794jggsa0v.apps.googleusercontent.com
            client-secret: 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
  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/Eat-Good-Naija
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8081
sha512:
  string: 5627dcc7bb45a7cf9ddd211168fb727a2005338c5fe1e29faa71fc542bcd59e1bf0c604d65578ba9001984bfa0f25e29a509f130db33c51916bf0ebfbb78b645
CLIENT:
  ID: 995760024175-tl4qnsoi4ecechr40hkeql794jggsa0v.apps.googleusercontent.com

# Paysatck details
applyforme:
  paystack:
    secret:
      key: sk_test_81d036c07aaa61c966c046aa1f8e3414acce1200